version: '3.8'
services:
  jass_gym:
    build:
      context: .
      network: host
    network_mode: host
    volumes:
      - .:/app
      - ./ray_results:/home/ray/ray_results
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities: [ gpu ]


